### PR TITLE
addison: README: use Moto's image URL

### PR DESCRIPTION
**Pull request by DroidThug**
* CyanogenMod is dead and so is it's wiki

### CODE REVIEW

**Comment by akhilnarang** [comment]
meh, push to lineage then :3

**Comment by DroidThug** [comment]
:'3 k

**Comment by DroidThug** [comment]
LineageOS/android_device_motorola_addison@f7ae055cea84640fb1a396eb9c7861e8eaa5d22c

:'v

**Comment by akhilnarang** [comment]
4
0
4

**Comment by jakubschenk** [comment]
NO U

**Comment by DroidThug** [comment]
@akhilnarang -_____________-

https://github.com/LineageOS/android_device_motorola_addison/commit/f7ae055cea84640fb1a396eb9c7861e8eaa5d22c

**Comment by akhilnarang** [comment]
@DroidThug edited ;_; lulzkbye

**Pull request closed without merging**
